#!/usr/bin/env python
"""What the learned acid-amine interaction axes correlate with.

    python scripts/interpret_phase4.py

Exploratory, correlational, and strictly downstream of the predictive result. A
latent coordinate that lines up with molecular weight does not mean the model
learned about sterics; it means the axis and the weight covary across 272
molecules. Nothing here feeds the decision rule.

Refits the low-rank pair model on one authoritative fold -- the same fold, the
same grid, the same selection on entity-OOD validation -- rotates the pair term
into the singular basis of ``W``, and correlates each axis against a descriptor
list fixed in advance. Writes `results/phase4_chemlex/axes.jsonl` and
`results/phase4_chemlex/summary/axes.md`.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
import torch

from intervention_algebra.real_data.chemlex import dataset as ds
from intervention_algebra.real_data.chemlex import experiment as ex
from intervention_algebra.real_data.chemlex import report as rp
from intervention_algebra.real_data.chemlex.interpret import (axis_correlations,
                                                              descriptors,
                                                              interaction_axes)
from intervention_algebra.real_data.chemlex.models import ModelConfig
from intervention_algebra.real_data.chemlex.splits import SELECT_BUCKETS
from intervention_algebra.real_data.chemlex.train import (TrainConfig,
                                                          fit_scaling,
                                                          make_batch,
                                                          train_with_grid)

OUT = Path("results/phase4_chemlex")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--screen", default="hatu")
    ap.add_argument("--partition", type=int, default=0)
    ap.add_argument("--fold", type=int, default=0)
    ap.add_argument("--q", type=float, default=0.05,
                    help="Benjamini-Hochberg cut for the reported table")
    ap.add_argument("--outdir", type=Path, default=OUT)
    args = ap.parse_args()
    torch.set_num_threads(4)

    spec = ex.Spec(block="primary", screen=args.screen, endpoint="yield",
                   partition=args.partition, fold=args.fold,
                   ladder=("lowrank",))
    prep = ex.prepare(spec, raw=ds.load_raw())
    fold = ex.fold_of(prep, spec)
    frame = prep.screen.frame
    y = frame["y"].to_numpy()
    tr, va = fold.mask("train"), fold.mask(SELECT_BUCKETS)
    scaling = fit_scaling(y[tr])
    btr = make_batch(frame["acid"][tr], frame["amine"][tr], frame["cond"][tr],
                     y[tr], scaling)
    bva = make_batch(frame["acid"][va], frame["amine"][va], frame["cond"][va],
                     y[va], scaling)
    cfg = ModelConfig(n_acids=len(prep.screen.acids),
                      n_amines=len(prep.screen.amines),
                      n_conditions=len(prep.screen.conditions),
                      x_acid=prep.acid_fp.x, x_amine=prep.amine_fp.x)
    fit = train_with_grid("lowrank", cfg, btr, bva, TrainConfig(),
                          seed=ex.hash_seed(spec), grid=ex._grid_for("lowrank"))
    axes = interaction_axes(fit.model)

    frames = []
    for role, key, smis in (("acid", "acid_axes", prep.screen.acids),
                            ("amine", "amine_axes", prep.screen.amines)):
        frames.append(axis_correlations(axes[key], descriptors(smis, role),
                                        role, n_axes=2))
    corr = pd.concat(frames, ignore_index=True)

    args.outdir.mkdir(parents=True, exist_ok=True)
    # Self-identifying, like every other result row in this directory: a file
    # in results/ that cannot say which phase and which block produced it is how
    # Phase 3's results went unindexed.
    (args.outdir / "axes.jsonl").write_text("".join(
        json.dumps({"key": f"axes/{args.screen}/{r['role']}/axis{int(r['axis'])}/"
                           f"{r['descriptor']}",
                    "block": "axes", "screen": args.screen,
                    "representation": "ecfp4", "endpoint": "yield", **r}) + "\n"
        for r in corr.to_dict("records")))

    sig = corr[corr["q"] < args.q].sort_values(["role", "axis", "p"])
    rows = [{"role": r["role"], "axis": int(r["axis"]),
             "descriptor": r["descriptor"], "entities": int(r["n"]),
             "Spearman rho": f"{r['rho']:+.3f}", "p": f"{r['p']:.3g}",
             "BH q": f"{r['q']:.3g}"}
            for r in sig.head(24).to_dict("records")]
    sv = axes["singular_values"]
    text = f"""*Generated by `scripts/interpret_phase4.py`. Exploratory and
correlational; nothing here feeds the decision rule.*

Refit on `{args.screen}`, partition {args.partition} fold {args.fold}, selected
hyperparameters {fit.hparams}. The pair term is rotated into the singular basis
of `W` before anything is reported, because `z_A^T W z_N` is invariant under
`z_A -> M z_A` with `W -> M^-T W`, so a raw encoder coordinate names an
arbitrary direction. Singular values {np.round(sv, 4).tolist()}, carrying
{np.round(axes['explained'], 3).tolist()} of the form.

Spearman correlations of each axis against a descriptor list fixed in advance,
Benjamini-Hochberg q < {args.q:g} over the whole table:

{rp.table(rows, ["role", "axis", "descriptor", "entities", "Spearman rho", "p", "BH q"])}

Signs are arbitrary: a singular vector is unique only up to sign, so read the
magnitude and the grouping, never the direction.
"""
    (args.outdir / "summary" / "axes.md").parent.mkdir(parents=True, exist_ok=True)
    (args.outdir / "summary" / "axes.md").write_text(text)
    print(f"singular values {np.round(sv, 4)} share {np.round(axes['explained'], 3)}")
    print(f"{len(sig)} of {len(corr)} correlations survive BH q < {args.q:g}")
    print(f"wrote {args.outdir / 'summary' / 'axes.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
